name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Build

      run: cargo build --verbose
    - name: Run tests Engine
      run: cargo test --test=test_engine --verbose
